spring:
  task:
    scheduling:
      pool:
        size: 2

driverName: org.apache.hive.jdbc.HiveDriver
#url: jdbc:hive2://10.179.132.112:10000/mobile_db;connectionTimeout=30000;
url: jdbc:hive2://.179.132.112:10000/mobile_db;connectionTimeout=300;
username: test
passwd: 123

#bootstrap.servers1: aiops-ss-kfk01:9094,aiops-ss-kfk02:9094,aiops-ss-kfk03:9094
#bootstrap.servers2: aiops-st-kfk01:9094,aiops-st-kfk02:9094,aiops-st-kfk03:9094
bootstrap.servers1: 127.0.0.1:9092
bootstrap.servers2: 127.0.0.1:9092
#topic: saas-metrics-aiops-servicesystem-rawdata
topic: test

dirTarget: /Users/wohaocai/Desktop/linsh1
dirSource: /Users/wohaocai/Desktop/linsh

#dirTarget: /root/yidongAlarm
#dirSource: /root/yidongAlarm1

#cron1: "5 1 4 * * *"
#cron2: "5 0,30 * * * *"
cron1: "5 */1 * * * *"
cron2: "20 */1 * * * *"

# application.yml 示例
logging:
  file:
    name: logs/application.log           # 日志文件路径
    # 日志文件最大大小
    max-size: 10MB
    # 保留的历史日志文件数
    max-history: 30
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"   # 控制台输出格式
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"      # 文件输出格式

